spring.application.name=dynamic-scheduler
# H2 Database Connection Setup
spring.datasource.url=jdbc:h2:mem:schedulerdblink;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Automatically creates the database tables based on your ClientScheduleConfig entity class
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Web Console for easy visual debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Fixes an H2 console loading bug inside modern browsers
spring.headers.frame-options=sameorigin
